### ISSUE TITLE
TemplateModifierBase with unwrapped modules

### ISSUE THREAD

**Issue by BryghtShadow** [RheingoldRiver/mwcleric#23]
When trying to use TemplateModifierBase on pages using raw `#invoke:`, the default check doesn't suffice: https://github.com/RheingoldRiver/mwcleric/blob/237876c6be4c0d960ad0b9a3bff0ed63472f8288/mwcleric/template_modifier.py#L45-L49

Here's a snippet that would run for Modules. If we also wish to allow for `#invoke:Foo` in the constructor, then `__init__` needs to be modified to handle `template` for `site.pages_using(template, namespace=namespace)`, as well as doing the below rename because mwpfh doesn't consider `template.name.matches('#invoke:Foo')` to be True.
```python
class TemplateModifier(TemplateModifierBase):
    def update_template(self, template):
        print(template.name) # prints "#invoke:Foo"
        return

    def update_wikitext(self, wikitext):
        for template in wikitext.filter_templates(recursive=self.recursive):
            hasMatch = False
            # required for modules, because "#invoke:" is not a valid namespace,
            # ensure we only modify {{#invoke:Foo}} and not {{Module:Foo}}
            # (( just in case someone is actually transcluding a module... ))
            if template.name.get(0).startswith('#invoke:'):
                # temp rename to Module:Foo, so that match can do its magic.
                template.name.replace('#invoke:', 'Module:')
                # mwpfh's loose equivalency test
                hasMatch = template.name.matches(self.template_name)
                # revert back to #invoke, otherwise we'd be transcluding the contents of the module.
                template.name.replace('Module:', '#invoke:')
            else:
                hasMatch = template.name.matches(self.template_name)
            if hasMatch:
                self.current_template = template
                self.update_template(template)
        return

TemplateModifier(site, 'Module:Foo').run() # OK
TemplateModifier(site, '#invoke:Foo').run() # "#invoke:" is not a valid namespace, so this would never match.
```

Maybe there could be a `ModuleModifierBase` class?

**Comment by RheingoldRiver** [comment]
This seems like a good change, but I think this is a bug with mwpfh and should be opened there, though we can have the code here too as a workaround until they patch it.

I'm slightly concerned that there might be some weird side effect here because of some unconsidered whitespace or other issue, though. Could we `copy.deepcopy()`  the template.name and do the replace and matches check on that? And then no need to replace back. Send a PR and I'll merge it.
